#!/bin/sh

#
#
#

for task_id in $(bioluigi list --status DISABLED "$1" | cut -f 1); do
    bioluigi reenable "$task_id" &
done

wait

for task_id in $(bioluigi list --status FAILED "$1" | cut -f 1); do
    bioluigi forgive "$task_id" &
done

wait
