#!/usr/bin/env python

import sys
from glob import glob
from os.path import basename, join

remapping_file = sys.argv[1]
reference_id = sys.argv[2]

remapping = {}
with open(remapping_file) as f:
    for line in f:
        a, b = line.strip().split('\t')
        remapping[a] = b

for expression_data_file in glob(join('pipeline-output/quantified', reference_id, "*.genes")):
    name = basename(expression_data_file)
    output_expression_data_file = join('pipeline-output/quantified', reference_id + "_fixed", name)
    print(name)
    with open(expression_data_file) as f, open(output_expression_data_file, 'w') as fout:
        header = True
        for line in f:
            if header:
                fout.write(line)
                header = False
                continue
            gene_id, rest = line.split('\t', maxsplit=1)
            if gene_id in remapping:
                gene_id = remapping[gene_id]
            fout.write(gene_id + '\t' + rest)
